[package]
name = "gennewpass"
version = "0.1.0"
authors = ["VMM <vladimirov.m.m@ya.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"